# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i61lvYkC2PrRuAr5akF5C0Dj3w-ows4G
"""

for i in range(10):
  print(i)

!git clone https://github.com/hammadmasud/29-febb.git